[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
license-file = "LICENSE"
edition = "2018"
readme = "README.md"


[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
stylist = { version = "0.8.0", features = ["yew_integration"] }
wasm-bindgen = "0.2"
yew = "0.18"
