[tasks.build]
install_crate = "trunk"
command = "trunk"
args = ["build", "--release"]

[tasks.serve]
install_crate = "trunk"
command = "trunk"
args = ["serve", "--open"]

[tasks.lint]
install_crate = "clippy"
command = "cargo"
args = ["clippy"]
dependencies = ["format"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]
